# Generated by Django 4.2.2 on 2023-06-25 20:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('max_seats', models.PositiveIntegerField()),
                ('min_seats', models.PositiveIntegerField()),
                ('table_number', models.PositiveIntegerField()),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.restaurant')),
            ],
        ),
    ]
