# Generated by Django 4.2.2 on 2023-06-25 20:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('booking', '0002_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('group_size', models.IntegerField()),
                ('time', models.CharField(choices=[('01', '1am'), ('02', '2am'), ('03', '3am'), ('04', '4am'), ('05', '5am'), ('06', '6am'), ('07', '7am'), ('08', '8am'), ('09', '9am'), ('10', '10am'), ('11', '11am'), ('12', '12pm'), ('13', '1pm'), ('14', '2pm'), ('15', '3pm'), ('16', '4pm'), ('17', '5pm'), ('18', '6pm'), ('19', '7pm'), ('20', '8pm'), ('21', '9pm'), ('22', '10pm'), ('23', '11pm'), ('24', '12am')], max_length=2)),
                ('date', models.DateField()),
                ('note', models.TextField(blank=True)),
                ('table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.table')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['date', 'time'],
            },
        ),
    ]
